workflows:
  android-workflow:
    name: Android Debug Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      java: 17
      vars:
        PACKAGE_NAME: "com.aquareminder.app"
      
    scripts:
      - name: Set up local.properties
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
          
      - name: Build Android debug APK
        script: | 
          cd $CM_BUILD_DIR
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace
          
    artifacts:
      - app/build/outputs/**/*.apk
      
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
